spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
#spring.datasource.password=password
spring.datasource.initialization-mode=always

server.servlet.session.cookie.http-only=false
server.servlet.session.cookie.secure=false

server.error.whitelabel.enabled=false
#logging.level.org.springframework.security=DEBUG
spring.profiles.active=prod

# EWC 526 - attack
management.endpoints.web.exposure.include=*

# EWC 526 - defense
#management.endpoint.env.enabled=false
#management.endpoints.web.exposure.include=health,info

# spring.h2.console.enabled=false

# 526 - 2. nacin
#server.error.include-stacktrace=never

# 260
spring.datasource.password=${DB_PASSWORD}

# CWE-260: Admin password loaded from environment variable (injected secret)
#secure.admin-password=${SECURE_ADMIN_PASSWORD}

# CWE-15
demo.debug-enabled=false
demo.maintenance-mode=true
